apiVersion: v1
kind: Service
metadata:
  name: postgresql-keycloak-service
spec:
  selector:
    service: keycloak-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
      name: postgres
  type: NodePort